version: 2
jobs:
  one:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run: echo "A first hello"
  two:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run: echo "Another hello"
workflows:
  version: 2
  one_and_two:
    jobs:
      - one
      - two