version: 2
jobs:
  app_test:
    docker:
     - image: circleci/golang:1.12
    steps:
      - checkout
      - run: go test ./...
  build:
    docker:
     - image: circleci/golang:1.12
    steps:
      - checkout
      - run: mkdir -p my_workspace
      - run: go build -o my_workspace/main
      - persist_to_workspace:
          root: my_workspace
          paths:
            - main
  deploy:
    docker:
     - image: circleci/python:2.7-jessie
    steps:
      - attach_workspace:
          at: my_workspace
      - run:
          name: install AWS CLI
          command: sudo pip install awscli
      - run:
          name: Deploy
          command: touch testfile.txt && aws s3 cp testfile.txt s3://omar-circleci-buil
workflows:
  version: 2
  learn_test_deploy:
    jobs:
      - app_test
      - build:
          requires:
            - app_test
      - deploy:
          requires:
            - build